import { useState } from 'react';
import type { StaffApiError, StaffUser } from '../../types/admin-user-management';

export function StaffStatusDialog({ staff, pending, error, onClose, onConfirm }: { staff: StaffUser; pending: boolean; error?: StaffApiError; onClose: () => void; onConfirm: () => Promise<void> }) {
  const [success, setSuccess] = useState(false);
  const activating = staff.accountStatus === 'inactive';
  const action = activating ? 'Activate' : 'Deactivate';
  const confirm = async () => { try { await onConfirm(); setSuccess(true); } catch { /* The parent exposes the safe request error. */ } };
  return <div className="fixed inset-0 z-50 flex items-end bg-slate-950/45 p-0 sm:items-center sm:justify-center sm:p-6" role="presentation"><div role="dialog" aria-modal="true" aria-labelledby="status-dialog-title" aria-describedby="status-dialog-description" className="w-full rounded-t-2xl bg-white p-5 shadow-2xl sm:max-w-md sm:rounded-2xl sm:p-6"><div className={`flex h-10 w-10 items-center justify-center rounded-full ${activating ? 'bg-emerald-100 text-emerald-800' : 'bg-amber-100 text-amber-800'}`} aria-hidden="true">{activating ? '+' : '−'}</div><h2 id="status-dialog-title" className="mt-4 text-lg font-semibold text-slate-950">{success ? `Account ${activating ? 'activated' : 'deactivated'}` : `${action} staff account?`}</h2><p id="status-dialog-description" className="mt-2 text-sm leading-6 text-slate-600">{success ? `${staff.name}'s account status has been updated with the server-confirmed result.` : activating ? `Restore sign-in access for ${staff.name}. Their account history remains unchanged.` : `Prevent ${staff.name} from signing in. Their account history will remain preserved.`}</p>{error && <p role="alert" className="mt-4 rounded-lg border border-red-200 bg-red-50 px-3 py-2.5 text-sm text-red-800">{error.message}</p>}<div className="mt-6 flex flex-col-reverse gap-3 sm:flex-row sm:justify-end"><button type="button" onClick={onClose} disabled={pending} className="min-h-11 rounded-lg border border-slate-300 px-4 text-sm font-semibold text-slate-700 hover:bg-slate-50 focus-visible:outline focus-visible:outline-2 focus-visible:outline-indigo-700">{success ? 'Done' : 'Cancel'}</button>{!success && <button type="button" onClick={() => void confirm()} disabled={pending} className={`min-h-11 rounded-lg px-4 text-sm font-semibold text-white focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 ${activating ? 'bg-emerald-700 hover:bg-emerald-800 focus-visible:outline-emerald-700' : 'bg-amber-700 hover:bg-amber-800 focus-visible:outline-amber-700'} disabled:cursor-not-allowed disabled:opacity-60`}>{pending ? `${action}ing…` : action}</button>}</div></div></div>;
}
