import type { ReactNode } from 'react';
import type { AdminSystemSettingsFormValues, SystemSettingsValidationErrors } from '../../types/admin-system-settings';

type Field = keyof AdminSystemSettingsFormValues;

function NumberField({ id, label, description, value, error, disabled, onChange }: { id: Field; label: string; description: string; value: string; error?: string; disabled: boolean; onChange: (field: Field, value: string) => void }) {
  return <div><label className="form-label" htmlFor={id}>{label} <span className="text-red-700">*</span></label><p id={`${id}-help`} className="mb-2 text-sm leading-5 text-slate-500">{description}</p><input id={id} className="form-input" type="number" min="0" step="any" inputMode="decimal" value={String(value)} disabled={disabled} aria-invalid={Boolean(error)} aria-describedby={error ? `${id}-error` : `${id}-help`} onChange={(event) => onChange(id, event.target.value)} />{error && <p id={`${id}-error`} className="field-error">{error}</p>}</div>;
}

function SettingsPanel({ title, description, children }: { title: string; description: string; children: ReactNode }) {
  return <section className="rounded-xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-200 px-5 py-4 sm:px-6"><h2 className="text-base font-semibold text-slate-950">{title}</h2><p className="mt-1 text-sm leading-6 text-slate-500">{description}</p></div><div className="p-5 sm:p-6">{children}</div></section>;
}

export function SystemSettingsForm({ values, errors, saving, onChange }: { values: AdminSystemSettingsFormValues; errors: SystemSettingsValidationErrors; saving: boolean; onChange: (field: Field, value: string) => void }) {
  return <div className="mt-7 grid gap-5 lg:grid-cols-2"><SettingsPanel title="Loan Settings" description="Configure the standard loan period used by the library policy."><NumberField id="loanPeriod" label="Loan period" description="Enter the loan period as a positive number of days." value={values.loanPeriod} error={errors.loanPeriod} disabled={saving} onChange={onChange} /></SettingsPanel><SettingsPanel title="Borrowing Limits" description="Configure the maximum number of items a member may borrow."><NumberField id="borrowingLimit" label="Borrowing limit" description="Enter a non-negative number of items." value={values.borrowingLimit} error={errors.borrowingLimit} disabled={saving} onChange={onChange} /></SettingsPanel><SettingsPanel title="Fine Rules" description="Configure policy values only; official fines are calculated by the backend."><div className="grid gap-5 sm:grid-cols-2"><NumberField id="fineRate" label="Fine rate" description="Enter a non-negative rate." value={values.fineRate} error={errors.fineRate} disabled={saving} onChange={onChange} /><NumberField id="fineCap" label="Fine cap" description="Enter a non-negative maximum fine." value={values.fineCap} error={errors.fineCap} disabled={saving} onChange={onChange} /></div></SettingsPanel><SettingsPanel title="Reservation Policy" description="Reservation queue decisions remain backend-controlled."><p className="rounded-lg border border-dashed border-slate-300 bg-slate-50 px-4 py-4 text-sm leading-6 text-slate-600">Reservation policy fields will appear after the confirmed backend contract is available.</p></SettingsPanel><SettingsPanel title="Seat Policy" description="Seat booking and conflict rules remain backend-controlled."><p className="rounded-lg border border-dashed border-slate-300 bg-slate-50 px-4 py-4 text-sm leading-6 text-slate-600">Seat policy fields will appear after the confirmed backend contract is available.</p></SettingsPanel></div>;
}
