import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import axios from 'axios';
import { AdminLayout } from '../admin/admin-layout';
import { StaffPageHeader } from '../admin-user-management/staff-ui';
import { adminSystemHealthService } from '../../services/admin-system-health-service';

const errorMessage = (error: unknown) => axios.isAxiosError(error) && [401, 403].includes(error.response?.status ?? 0) ? 'You do not have permission to update AI settings.' : 'AI settings could not be updated. The saved setting has not changed.';

export function AiSettingsPage() {
  const client = useQueryClient();
  const settings = useQuery({ queryKey: ['admin', 'ai-settings'], queryFn: adminSystemHealthService.getAiSettings, retry: 1 });
  const [saved, setSaved] = useState(false);
  const update = useMutation({ mutationFn: adminSystemHealthService.updateAiSettings, onSuccess: (data) => { client.setQueryData(['admin', 'ai-settings'], data); client.invalidateQueries({ queryKey: ['admin', 'system-health'] }); setSaved(true); } });
  const enabled = settings.data?.enabled;
  const toggle = (next: boolean) => { setSaved(false); update.mutate({ enabled: next }); };
  return <AdminLayout><StaffPageHeader title="AI Settings" description="Control whether optional AI assistance is available. Library operations and official records remain rule-based." />{settings.isLoading ? <section className="mt-7 h-56 animate-pulse rounded-xl border border-slate-200 bg-white shadow-sm" /> : settings.isError ? <section className="mt-7 rounded-xl border border-red-200 bg-red-50 p-5"><h2 className="font-semibold text-red-950">AI settings are unavailable</h2><p role="alert" className="mt-2 text-sm text-red-800">Unable to load the persisted AI setting. Please try again.</p><button type="button" onClick={() => void settings.refetch()} className="mt-4 min-h-10 rounded-lg border border-red-300 bg-white px-3.5 text-sm font-semibold text-red-900 hover:bg-red-50">Retry</button></section> : enabled !== undefined ? <section className="mt-7 max-w-3xl rounded-xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="flex flex-col gap-6 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-lg font-semibold text-slate-950">AI assistance</h2><p id="ai-assistance-description" className="mt-1 max-w-xl text-sm leading-6 text-slate-600">When disabled, the system does not make AI provider calls. Search and other critical library operations continue through their deterministic behavior.</p></div><label className="inline-flex min-h-11 items-center gap-3 self-start rounded-lg border border-slate-200 bg-slate-50 px-3 py-2 text-sm font-semibold text-slate-800"><input type="checkbox" role="switch" checked={enabled} disabled={update.isPending} aria-describedby="ai-assistance-description" onChange={(event) => toggle(event.target.checked)} className="h-5 w-5 accent-indigo-700 focus-visible:outline focus-visible:outline-2 focus-visible:outline-indigo-700 disabled:cursor-not-allowed" /><span>{update.isPending ? 'Saving…' : enabled ? 'Enabled' : 'Disabled'}</span></label></div><div className={`mt-6 rounded-lg border p-4 text-sm leading-6 ${enabled ? 'border-emerald-200 bg-emerald-50 text-emerald-900' : 'border-slate-300 bg-slate-50 text-slate-800'}`} role="status"><span className="font-semibold">AI is {enabled ? 'enabled' : 'disabled'}.</span> {enabled ? 'Optional AI assistance may be used where configured.' : 'The library remains available; only optional AI assistance is unavailable.'}</div>{saved && <p role="status" className="mt-4 text-sm font-medium text-emerald-800">AI setting saved successfully.</p>}{update.isError && <p role="alert" className="mt-4 text-sm font-medium text-red-800">{errorMessage(update.error)}</p>}</section> : null}</AdminLayout>;
}
