import { useQuery } from '@tanstack/react-query';
import axios from 'axios';
import { AdminLayout } from '../admin/admin-layout';
import { StaffPageHeader } from '../admin-user-management/staff-ui';
import { adminSystemHealthService } from '../../services/admin-system-health-service';
import type { AIFeedbackResponse, SystemHealthResponse } from '../../types/admin-system-health';

const number = (value: number) => new Intl.NumberFormat().format(value);
const errorMessage = (error: unknown, fallback: string) => axios.isAxiosError(error) && [401, 403].includes(error.response?.status ?? 0) ? 'You do not have permission to view this information.' : fallback;

function MetricCard({ label, value, detail, loading }: { label: string; value: number; detail: string; loading?: boolean }) {
  return <article className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm">{loading ? <><div className="h-4 w-28 animate-pulse rounded bg-slate-200" /><div className="mt-5 h-8 w-16 animate-pulse rounded bg-slate-100" /></> : <><p className="text-sm font-medium text-slate-600">{label}</p><p className="mt-4 text-3xl font-semibold tracking-tight text-slate-950">{number(value)}</p><p className="mt-2 text-xs leading-5 text-slate-500">{detail}</p></>}</article>;
}

function HealthContent({ data }: { data: SystemHealthResponse }) {
  return <><section className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-3"><MetricCard label="API errors" value={data.application.apiErrors} detail="Recorded application/API errors" /><MetricCard label="Notification failures" value={data.notifications.deliveryFailures} detail="Recorded delivery failures" /><MetricCard label="AI usage" value={data.ai.usage} detail="Recorded successful AI use" /></section><section className="mt-6 grid gap-6 xl:grid-cols-[0.95fr_1.05fr]"><article className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-lg font-semibold text-slate-950">AI operational status</h2><p className="mt-1 text-sm leading-6 text-slate-600">Current backend-controlled availability. Core library rules continue without AI.</p></div><span className={`inline-flex items-center gap-2 rounded-full border px-3 py-1 text-xs font-semibold ${data.ai.enabled ? 'border-emerald-200 bg-emerald-50 text-emerald-800' : 'border-slate-300 bg-slate-100 text-slate-700'}`}><span className={`h-2 w-2 rounded-full ${data.ai.enabled ? 'bg-emerald-600' : 'bg-slate-500'}`} />AI {data.ai.enabled ? 'enabled' : 'disabled'}</span></div><dl className="mt-6 grid gap-4 sm:grid-cols-2"><div><dt className="text-sm text-slate-600">AI errors</dt><dd className="mt-1 text-2xl font-semibold text-slate-950">{number(data.ai.errors)}</dd></div><div><dt className="text-sm text-slate-600">Fallback used</dt><dd className="mt-1 text-2xl font-semibold text-slate-950">{number(data.ai.fallbackUsed)}</dd></div></dl></article><article className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><h2 className="text-lg font-semibold text-slate-950">AI error details</h2><p className="mt-1 text-sm leading-6 text-slate-600">Disabled AI is a setting, not a provider failure.</p><dl className="mt-6 grid gap-4 sm:grid-cols-3"><div><dt className="text-sm text-slate-600">Provider failures</dt><dd className="mt-1 text-2xl font-semibold text-slate-950">{number(data.ai.providerFailures)}</dd></div><div><dt className="text-sm text-slate-600">Timeouts</dt><dd className="mt-1 text-2xl font-semibold text-slate-950">{number(data.ai.timeouts)}</dd></div><div><dt className="text-sm text-slate-600">Unavailable</dt><dd className="mt-1 text-2xl font-semibold text-slate-950">{number(data.ai.unavailable)}</dd></div></dl></article></section><p className="mt-5 text-sm text-slate-500">Health events are retained for {number(data.retentionDays)} days.</p></>;
}

function Feedback({ data, loading, error, retry }: { data?: AIFeedbackResponse; loading: boolean; error: boolean; retry: () => void }) {
  return <section className="mt-6 rounded-xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><h2 className="text-lg font-semibold text-slate-950">Aggregated AI quality feedback</h2><p className="mt-1 text-sm leading-6 text-slate-600">Helpful and Not Helpful totals only. This view does not expose member information or change library records.</p></div>{error && <button type="button" onClick={retry} className="min-h-10 rounded-lg border border-slate-300 px-3 text-sm font-semibold text-slate-700 hover:bg-slate-50">Retry feedback</button>}</div>{loading ? <div className="mt-6 grid gap-4 sm:grid-cols-2"><div className="h-24 animate-pulse rounded-lg bg-slate-100" /><div className="h-24 animate-pulse rounded-lg bg-slate-100" /></div> : error ? <p role="alert" className="mt-5 rounded-lg border border-red-200 bg-red-50 p-4 text-sm text-red-800">AI feedback data is unavailable. Please try again.</p> : data ? <><div className="mt-6 grid gap-4 sm:grid-cols-2"><MetricCard label="Helpful" value={data.helpful} detail="Positive quality feedback" /><MetricCard label="Not Helpful" value={data.notHelpful} detail="Quality feedback requiring review" /></div>{data.helpful === 0 && data.notHelpful === 0 && <p className="mt-5 rounded-lg border border-dashed border-slate-300 px-4 py-4 text-sm text-slate-600">No AI feedback has been recorded in the current retention period.</p>}<p className="mt-4 text-sm text-slate-500">Feedback is retained for {number(data.retentionDays)} days.</p></> : null}</section>;
}

export function SystemHealthPage() {
  const health = useQuery({ queryKey: ['admin', 'system-health'], queryFn: adminSystemHealthService.getSystemHealth, retry: 1 });
  const feedback = useQuery({ queryKey: ['admin', 'ai-feedback'], queryFn: adminSystemHealthService.getAiFeedback, retry: 1 });
  return <AdminLayout><StaffPageHeader title="System Health" description="Read-only application, notification, and AI status from persisted system records." action={<button type="button" onClick={() => { void health.refetch(); void feedback.refetch(); }} className="min-h-11 rounded-lg border border-slate-300 bg-white px-4 text-sm font-semibold text-slate-800 hover:bg-slate-50 focus-visible:outline focus-visible:outline-2 focus-visible:outline-indigo-700">Refresh status</button>} />{health.isLoading ? <section className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{Array.from({ length: 3 }, (_, index) => <MetricCard key={index} label="" value={0} detail="" loading />)}</section> : health.isError ? <section className="mt-7 rounded-xl border border-red-200 bg-red-50 p-5"><h2 className="font-semibold text-red-950">System health is unavailable</h2><p role="alert" className="mt-2 text-sm leading-6 text-red-800">{errorMessage(health.error, 'System health data could not be loaded. Please try again.')}</p><button type="button" onClick={() => void health.refetch()} className="mt-4 min-h-10 rounded-lg border border-red-300 bg-white px-3.5 text-sm font-semibold text-red-900 hover:bg-red-50">Retry</button></section> : health.data ? <HealthContent data={health.data} /> : null}<Feedback data={feedback.data} loading={feedback.isLoading} error={feedback.isError} retry={() => void feedback.refetch()} /></AdminLayout>;
}
